apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: post-promotion-poc
spec:
  arguments:
    parameters:
      - name: APP_NAME
      - name: APP_NAMESPACE
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: sync
            templateRef:
              name: argo-hub.argocd.0.0.1
              template: sync
            arguments:
              parameters:
                - name: app
                  value: '{{workflow.parameters.APP_NAME}}'
                - name: flags
                  value: '--prune --timeout 120'
                - name: serverUrl
                  value: 'argo-cd-server.{{workflow.parameters.APP_NAMESPACE}}.svc.cluster.local'
                - name: opts
                  value: '--grpc-web --plaintext'
                - name: tokenSecret
                  value: 'argocd-token'
                - name: tokenSecretKey
                  value: 'token'
          - name: wait
            templateRef:
              name: argo-hub.argocd.0.0.1
              template: wait
            arguments:
              parameters:
                - name: app
                  value: '{{workflow.parameters.APP_NAME}}'
                - name: flags
                  value: '--health --timeout 120'
                - name: serverUrl
                  value: 'argo-cd-server.{{workflow.parameters.APP_NAMESPACE}}.svc.cluster.local'
                - name: opts
                  value: '--grpc-web --plaintext'
                - name: tokenSecret
                  value: 'argocd-token'
                - name: tokenSecretKey
                  value: 'token'
            depends: sync
          - name: send-message
            templateRef:
              name: argo-hub.slack.0.0.2
              template: send-message
            arguments:
              parameters:
                - name: SLACK_HOOK_URL
                  value: 'https://hooks.slack.com/services/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'
                - name: SLACK_TEXT
                  value: 'Successfully promoted {{workflow.parameters.APP_NAME}}!'
            depends: wait
