apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: demo
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-742b38ae-d7ee-40b3-9a0d-a2046a9e9161
      eventName: github-742b38ae-d7ee-40b3-9a0d-a2046a9e9161
      eventSourceName: demo
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
  triggers:
    - template:
        name: ci
        conditions: github-742b38ae-d7ee-40b3-9a0d-a2046a9e9161
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: demo-ci-
              spec:
                arguments:
                  parameters:
                    - name: REPO
                      value: ''
                workflowTemplateRef:
                  name: globex-ci
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-742b38ae-d7ee-40b3-9a0d-a2046a9e9161
                dataTemplate: >-
                  https://github.com/codefresh-contrib/python-flask-sample-app.git
