apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: demo-nov-22
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-0560c405-ec74-4e8c-bcda-b3ef2cbcc23c:
      events:
        - push
      repositories:
        - owner: aperture-sci
          names:
            - CorpSite
      webhook:
        port: '80'
        method: POST
        endpoint: >-
          /webhooks/gitops/demo-nov-22/github-0560c405-ec74-4e8c-bcda-b3ef2cbcc23c
        url: https://641dfab29939b208915c0d4e-gitops.tunnels.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: runtime-repo-creds-secret
        key: password
